apiVersion: v1
kind: Service
metadata:
  name: webapp-color-service
  namespace: quiz-pnt
spec:
  type: LoadBalancer 
  selector:
    app: webapp-color 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080